global:
  smtp_smarthost: 'hosthere'
  smtp_from: 'fromhere'
  smtp_auth_username: 'usernamehere'
  smtp_auth_password: 'passwordhere'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-alerts'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    repeat_interval: 5m
  - match:
      severity: warning
    receiver: 'warning-alerts'
    repeat_interval: 30m

receivers:
- name: 'email-alerts'
  email_configs:
  - to: 'email@gmail.com'
    html: |
      <h2>🔔 Alert: {{ .GroupLabels.alertname }}</h2>
      <ul>
      {{ range .Alerts }}
      <li><strong>{{ .Annotations.summary }}</strong><br>
      Instance: {{ .Labels.instance }}<br>
      Started: {{ .StartsAt }}</li>
      {{ end }}
      </ul>

- name: 'critical-alerts'
  email_configs:
  - to: 'email@gmail.com'
    html: |
      <h1 style="color:red;">🚨 CRITICAL ALERT</h1>
      <h2>{{ .GroupLabels.alertname }}</h2>
      <ul>
      {{ range .Alerts }}
      <li><strong style="color:red;">{{ .Annotations.summary }}</strong><br>
      Instance: {{ .Labels.instance }}<br>
      Started: {{ .StartsAt }}</li>
      {{ end }}
      </ul>

- name: 'warning-alerts'
  email_configs:
  - to: 'email@gmail.com'
    html: |
      <h2 style="color:orange;">⚠️ WARNING</h2>
      <h3>{{ .GroupLabels.alertname }}</h3>
      <ul>
      {{ range .Alerts }}
      <li><strong>{{ .Annotations.summary }}</strong><br>
      Instance: {{ .Labels.instance }}<br>
      Started: {{ .StartsAt }}</li>
      {{ end }}
      </ul>

inhibit_rules:
- source_match:
    alertname: 'InstanceDown'
  target_match_re:
    instance: '.*'
  equal: ['instance']