services:
    minio:
        image: quay.io/minio/minio
        ports:
            - 9000:9000
            - 9001:9001
        command: server /data --console-address ":9001"
        environment:
            MINIO_ROOT_USER: ${MINIO_USER}
            MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
            MINIO_SERVER_URL: https://s3.vicisportscience.com
            MINIO_BROWSER_REDIRECT_URL: http://vici:9001
        volumes:
            - /root/minio/data:/data