services:
    redis:
        image: redis:latest
        ports:
        - "6379:6379"
        command: redis-server /usr/local/etc/redis/redis.conf
        volumes:
        - /root/redis/data:/root/redis
        - /root/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - /root/redis/certs/redis.key:/usr/local/etc/redis/redis.key
        - /root/redis/certs/redis.crt:/usr/local/etc/redis/redis.crt
        - /root/redis/certs/rootca.crt:/usr/local/etc/redis/rootca.crt